sudo: true

language: node_js
node_js:
  - '14.15.4'

branches:
  only:
    - main
  
cache:
  directories:
    - node_modules


before_install:
  - npm update
install:
  - npm install
before_script: 
  # To make sure that mocha has the rights to be run.
  - chmod 0777 ./node_modules/.bin/mocha
  - npm run build
script:
  - npm test

notifications:  
  email:  
    recipients:  
    - dominik.hillmann.wzl@gmail.com
    on_success: always  
    on_failure: always